### ISSUE TITLE
Photos should scroll to allow for more space on the instructions

### ISSUE THREAD

**Issue by pcresswell** [katrinsharp/becipe#11]
While the photos are good, I think there are some improvements we could make. Three options:
1. Fix the photos in place. This allows the instructions to take more space which is ultimately what people are going to need to read to complete the recipes.
2. Have the ability to overlay instructions on photos and then make the photos the central way to describe steps in the recipe. I think this would look visually nice but I doubt users would ever contribute enough photos for a 1 to 1 match between photos and steps.
3. Allow users to embed photos inside the steps instead of just at the top as a slider.

**Comment by pcresswell** [comment]
I think for now we can go with option 1 to keep it simple and still get the value of the photos.

**Comment by katrinsharp** [comment]
#9 is about the point number 1.
