### ISSUE TITLE
Create confirmation and thank you emails for signup

### ISSUE THREAD

**Issue by pcresswell** [katrinsharp/becipe#25]
Need to create a confirmation and thank you email for signup process.

**Comment by pcresswell** [comment]
Need to keep it simple.  I like the mailchimp simplicity.
![screen shot 2013-08-12 at 11 40 12 am](https://f.cloud.github.com/assets/1090039/948354/0453715c-0366-11e3-8579-0012e215c915.png)

**Comment by pcresswell** [comment]
Current Email:

> We've almost finished.
> Now we need to confirm your email address so we've sent you an email. Please check your inbox to complete the signup.
> Happy mixing!
> The Becipe Team

This is good. Simple. Lets try and have a bit of fun:

> We're almost done! Just one more ingredient is needed.
> 
> We just sent you a confirmation email. Please check your inbox and click on the big "Confirm Registration" button to open your account.
> 
> Happy mixing!
> The Becipe Team

**Comment by katrinsharp** [comment]
to activate your account instead of open an account, maybe?

**Comment by pcresswell** [comment]
"Activate" is much better.  Yes.

**Comment by pcresswell** [comment]
Also, here is the current "Thank you" text.

> Congradulations peter!
> The account was successfully confirmed.
> Let's get started. What about creating your first Becipe?
> Happy mixing!
> The Becipe Team

Suggest changing to:

> Congratulations Peter!
> Your account is confirmed.
> Let's get started. How about creating your first Becipe?
> Happy mixing!
> The Becipe Team

Just a spelling correction, capitalization on first name and the rest. Really like the prompt to create the first recipe.

**Comment by pcresswell** [comment]
![screen shot 2013-08-15 at 6 00 04 pm](https://f.cloud.github.com/assets/1090039/972218/2138e558-05f6-11e3-8c96-038a410059a2.png)

Feedback?

**Comment by katrinsharp** [comment]
I believe we need to call the user by name he has submitted. Something
like: Hi Peter, almost done etc

On Thu, Aug 15, 2013 at 6:00 PM, pcresswell notifications@github.comwrote:

> [image: screen shot 2013-08-15 at 6 00 04 pm]https://f.cloud.github.com/assets/1090039/972218/2138e558-05f6-11e3-8c96-038a410059a2.png
> 
> Feedback?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/katrinsharp/becipe/issues/25#issuecomment-22734034
> .

## 

Best Regards,
Katrin

**Comment by pcresswell** [comment]
Good idea. More personal.

--Peter

On 2013-08-16, at 3:45 AM, Katrin notifications@github.com wrote:

I believe we need to call the user by name he has submitted. Something
like: Hi Peter, almost done etc

On Thu, Aug 15, 2013 at 6:00 PM, pcresswell notifications@github.comwrote:

> [image: screen shot 2013-08-15 at 6 00 04 pm]<
> https://f.cloud.github.com/assets/1090039/972218/2138e558-05f6-11e3-8c96-038a410059a2.png>
> 
> Feedback?
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/katrinsharp/becipe/issues/25#issuecomment-22734034>
> .

## 

Best Regards,
Katrin

—
Reply to this email directly or view it on
GitHubhttps://github.com/katrinsharp/becipe/issues/25#issuecomment-22752222
.
