### ISSUE TITLE
More users would sign up if they better understood what Becipe was about

### ISSUE THREAD

**Issue by pcresswell** [katrinsharp/becipe#3]
Lets add a strong large banner type message across the top of the site under the header.  Let's try "Get great healthy skin without the nasty chemicals by using these fun skin care recipes."

**Comment by pcresswell** [comment]
Here is what I would like to say:

_Becipe is all about helping you get great, healthy skin through home made skin care. Here's how it works._

_1. Find a recipe you would like to try._
_2. Purchase the ingredients on your own or buy the Becipe kit._
_3. Follow the step by step instructions on the recipe._

_Have a recipe you would like to share? Sign up and create a recipe on our site and share it with your friends._

**Sign Up** button

**Comment by pcresswell** [comment]
I've been thinking about where to put this. This needs to be pretty clear, top left sort of thing.  To start we can replace our existing "Welcome to Becipe" tile.  But I think we need something bigger than that. It feels like this tile needs to be at least 2 tiles wide and 2 tiles high and positioned on the top left. This would probably break the responsiveness somewhat but I think it might be worth trying.

**Comment by katrinsharp** [comment]
Agree about the size, I guess 2x3 not to be square. I'm inclined to leave 'Welcome to Becipe' in place because I believe it adds a great personal touch to the home page.

**Comment by pcresswell** [comment]
We can keep the welcome but let's make the bigger message on the top left. Higher visual traffic.

**Comment by katrinsharp** [comment]
Can we close this one in present of new design and favor of more specific hypothesises?
