### ISSUE TITLE
After creating recipe, main home page recipes don't load

### ISSUE THREAD

**Issue by pcresswell** [katrinsharp/becipe#33]
I just created a recipe on staging.  Nothing complicated.  It showed up just fine. I then clicked on one of the tags. Brought to the home page. Noticed that the display is not showing recipes anymore.  See screen shot.

Actually, it looks like the recipes just aren't loading at all. Testing in a new browser and noticed that the recipes aren't loading there either. May not be related to the above after all.

**Comment by pcresswell** [comment]
![screen shot 2013-09-04 at 11 57 24 am](https://f.cloud.github.com/assets/1090039/1081737/5b5d9848-157b-11e3-8112-4ee1fe8c763e.png)

**Comment by katrinsharp** [comment]
Looks like the issue is gone after I pushed the recent changes. Since it is a big chunk of changes, there is no point to try to understand why it happened before..
