### ISSUE TITLE
When loading staging site, only 'My First Recipe" is showing

### ISSUE THREAD

**Issue by pcresswell** [katrinsharp/becipe#34]
The rest are not loading.

**Comment by katrinsharp** [comment]
There is no rest.. -:) The database contains only one right now. We'll make sure that the prod has enough for the home page though.

**Comment by pcresswell** [comment]
What about when I filter and there is only a couple of recipes for that
filter?

--Peter

On 2013-09-06, at 11:33 AM, Katrin notifications@github.com wrote:

There is no rest.. -:) The database contains only one right now. We'll make
sure that the prod has enough for the home page though.

—
Reply to this email directly or view it on
GitHubhttps://github.com/katrinsharp/becipe/issues/34#issuecomment-23948494
.

**Comment by katrinsharp** [comment]
Didn't mean to close it. only comment.. As to your question, it is being held differently than the home page and should work for any number of recipes correctly.
