### ISSUE TITLE
Unexpectedly being asked to login

### ISSUE THREAD

**Issue by pcresswell** [katrinsharp/becipe#36]
I am being asked to login when I am already logged in. 

Reproduce:
1. Log in.
2. Create a recipe.
3. Click on the user name under the new recipe created.

You are then asked to log in again even though you already are logged in.  Wasn't expecting that. I assumed I would see recipes from that user or some kind of profile page (although at this point, I figured we might just show all recipes by this user or something easy like that).  Either way, wasn't expecting to be asked to log in again.
![screen shot 2013-09-06 at 1 20 57 pm](https://f.cloud.github.com/assets/1090039/1097970/1f14c89e-1719-11e3-9436-0bea7e10cec0.png)
![screen shot 2013-09-06 at 1 24 13 pm](https://f.cloud.github.com/assets/1090039/1097973/2ecce848-1719-11e3-941d-aa0a607ebebf.png)

**Comment by katrinsharp** [comment]
you're right about your assumption. right now any unimplemented route leads to login, it's better to give general unimplemented page instead.

**Comment by katrinsharp** [comment]
changed to show user public profile - right now recipes from this user.
