### ISSUE TITLE
Tooltips are hiding text to be entered

### ISSUE THREAD

**Issue by pcresswell** [katrinsharp/becipe#38]
I'm not a fan of the tool tip. I get the idea for sure and it's helpful where things aren't obvious (like entering ingredients with comma separation) but the implementation gets in the way (make your window half size for example as seen in the screenshot) and is a bit difficult to read (small font).  

We should think of a better approach in the future.

![screen shot 2013-09-06 at 1 39 02 pm](https://f.cloud.github.com/assets/1090039/1098100/89e6d73c-171b-11e3-9a02-b394901e25f6.png)

**Comment by katrinsharp** [comment]
It's gonna change actually for the reasons you've mentioned. We're planning labels and hints on the page and get rid of tooltip.

**Comment by katrinsharp** [comment]
removed a tooltips completely, now we have static labels and hints.
