### ISSUE TITLE
Trying to create recipe receive Exception message when posting

### ISSUE THREAD

**Issue by pcresswell** [katrinsharp/becipe#39]
Nothing particularly interesting about the recipe I was trying to create but when I press "Save" I get the message as seen on the screenshot.
![screen shot 2013-09-06 at 1 44 32 pm](https://f.cloud.github.com/assets/1090039/1098139/24b6cbdc-171c-11e3-8b87-325b3e0ff8ab.png)

**Comment by pcresswell** [comment]
All fields were filled in.

**Comment by pcresswell** [comment]
![screen shot 2013-09-06 at 1 47 44 pm](https://f.cloud.github.com/assets/1090039/1098169/74ff69a0-171c-11e3-9a5d-7045da757806.png)

More screenshot for documentation purposes

**Comment by katrinsharp** [comment]
caused by intermediate cookie that had only token and not user id - could happened only on one of our laptops during dev stage. not applicable to any real user.
