### ISSUE TITLE
Change ingredient list approach to remove comma as reserved character

### ISSUE THREAD

**Issue by pcresswell** [katrinsharp/becipe#40]
Low priority for sure for now but when I was trying to copy a recipe from the Mountain Rose Herb guys, I noticed that their ingredient list will sometimes allow for options.  For example:

> 20 drops citrus essential oil of choice or a blend of Sweet Orange, Grapefruit, Mandarin, and/or Tangerine

In our case, this would split.  Consider implementing a system for adding ingredients one at a time instead of all at once and splitting later. Same probably applies across the board (tags might benefit from same approach but that's stretching it for sure as we probably don't want comma characters in our tags).

**Comment by katrinsharp** [comment]
changed ingredients to be newline separated
