### ISSUE TITLE
Selecting categories changes page but does not scroll to the top

### ISSUE THREAD

**Issue by pcresswell** [katrinsharp/becipe#49]
When you pick a category ("men's care" for example), the page contents do change but the scroll location does not. So if you scroll to the bottom of the page then pick a category, the page contents above change but you won't notice since you are at the bottom of the page and can barely see the contents above.  

Suggest scrolling to the top instead when picking a category or in general, changing pages.

**Comment by katrinsharp** [comment]
on page change, the page returns to top.
